### ISSUE TITLE
Python version supported

### ISSUE THREAD

**Issue by xmnlab** [pyOpenSci/cookiecutter-pyopensci#17]
would be good to support just the most recent python versions?
currently tox.ini inside the template support 2.7, 3.4, 3.5, 3.6 
I am biased to support just 3.6, 3.7 and 3.8

another option would be the user select the python version supported for their project

any thought?

**Comment by choldgraf** [comment]
+1 from me - and in fact perhaps we want to make this part of the POS guidelines? Something like "Most projects should aim to support the latest 3 major versions of Python"?

**Comment by xmnlab** [comment]
That sounds good to me. I can work on that :)
