### ISSUE TITLE
Add a description of the generated template files

### ISSUE THREAD

**Issue by choldgraf** [pyOpenSci/cookiecutter-pyopensci#9]
It'd be useful to keep a page that describes that each of the files generated in the template is used for. E.g. we should show a tree output:

```
python_boilerplate/
├── CONTRIBUTING.rst
├── CONTRIBUTORS.rst
├── docs
│   ├── conf.py
│   ├── contributing.rst
│   ├── contributors.rst
│   ├── history.rst
│   ├── index.rst
│   ├── installation.rst
│   ├── make.bat
│   ├── Makefile
│   ├── readme.rst
│   └── usage.rst
├── HISTORY.rst
├── LICENSE
├── Makefile
├── MANIFEST.in
├── python_boilerplate
│   ├── __init__.py
│   └── python_boilerplate.py
├── README.rst
├── requirements_dev.txt
├── setup.cfg
├── setup.py
├── tests
│   └── test_python_boilerplate.py
└── tox.ini
```

and make sure we link out or have a description for each major thing that's there. Maybe this already exists for the original cookiecutter?

**Comment by kysolvik** [comment]
I like this idea. I don't think there's anything in the original cookiecutter-pypackage (I more or less directly ported the documentation). I'll work on putting something together and adding it to the docs

**Comment by kysolvik** [comment]
Done #10
